//types contract

export const TRANSACTION_PENDING = "TRANSACTION_PENDING";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";

export const READ_ARTICLES = "READ_ARTICLES";
